### ISSUE TITLE
Unfortunately, its no longer working !

### ISSUE THREAD

**Issue by SamRepository** [AaqibAhamed/Decrypt-PluralSight-Videos#1]
It looks like Pluralsight has updated the encryption algorithm. Decryption is complete but videos won't open (file can't be rendered)!

**Comment by AaqibAhamed** [comment]
Thank you for your feedback.It's not working now after plural sight new update.I'm going to fix it after stable relaese of plural sight. Keep in touch for new bug fixed releases.

**Comment by AaqibAhamed** [comment]
Find latest version in https://github.com/AaqibAhamed/Decrypt-PluralSight-Videos/tree/bugfix

**Comment by AaqibAhamed** [comment]
Find latest version in https://github.com/AaqibAhamed/Decrypt-PluralSight-Videos/tree/bugfix
