### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Oluadepe** [AaqibAhamed/Decrypt-PluralSight-Videos#4]
The link to download has been pulled down. You can share the the executable file link via email or google drive. My email is oluwaseun001@gmail.com @AaqibAhamed

**Comment by mrvogiacu** [comment]
> The link to download has been pulled down. You can share the the executable file link via email or google drive. My email is [oluwaseun001@gmail.com](mailto:oluwaseun001@gmail.com) @AaqibAhamed

try it

`https://github.com/dhorseman1710/Decrypt-PluralSight-GUI`

**Comment by AaqibAhamed** [comment]
I'm going to update the latest version.

**Comment by AaqibAhamed** [comment]
Find the latest version in https://github.com/AaqibAhamed/Decrypt-PluralSight-Videos/tree/bugfix
