### ISSUE TITLE
request updated decryptor

### ISSUE THREAD

**Issue by evansMensahGand** [AaqibAhamed/Decrypt-PluralSight-Videos#5]
Hello legend,  could  we have a decryptor for latest  Version 1.0.291.0 , please.

Thanks for your massive work, salute!

**Comment by mrvogiacu** [comment]
> Hello legend, could we have a decryptor for latest Version 1.0.291.0 , please.
> 
> Thanks for your massive work, salute!

did you check this issue?
`https://github.com/AaqibAhamed/Decrypt-PluralSight-Videos/issues/2`

**Comment by AaqibAhamed** [comment]
Find the latest version in https://github.com/AaqibAhamed/Decrypt-PluralSight-Videos/tree/bugfix
