### ISSUE TITLE
WTF, you copy my code and put your name in author?

### ISSUE THREAD

**Issue by mrvogiacu** [AaqibAhamed/Decrypt-PluralSight-Videos#6]

**Comment by AaqibAhamed** [comment]
yeah.. u said that if share code may cause issue from pluralsight that's why.. since it's not commercial ..i did.it's transparent to u also.. because i thought and I scared to put ur name there.. what to do now

**Comment by AaqibAhamed** [comment]
> _No description provided._

also i mentioned refreence and copyrightt as same

**Comment by AaqibAhamed** [comment]
reply ASAP

**Comment by mrvogiacu** [comment]
You can share, but you can't erase all author and write your name

**Comment by AaqibAhamed** [comment]
> You can share, but you can't erase all author and write your name

i thought if it is under my repo i put mine  because any issue cause u can't be responsible  ..that's y.. if i fix futre bug can i add my name also??

**Comment by AaqibAhamed** [comment]
see with #3 #be2d1d94f2460adb633ce7cb8d1b827809c2e8ff
