### ISSUE TITLE
Decryped Video Is not loading 

### ISSUE THREAD

**Issue by AabidAMajeed** [AaqibAhamed/Decrypt-PluralSight-Videos#7]
Hi after we decrypt the folder and videos are all structured and listed however, the videos cannot be played.

**Comment by DHuang888** [comment]
Have you tried Version 1.9.2 ?

**Comment by swapniladmulwar** [comment]
This file isn't playable. That might be because the file type is unsupported, the file extension is incorrect, or the file is corrupt.

Getting this error. Can you please help me here? I need it
