### ISSUE TITLE
Decypted file not playing

### ISSUE THREAD

**Issue by tdammy92** [AaqibAhamed/Decrypt-PluralSight-Videos#9]
Hello, please i need help with this. i decrpted the videos, but when i try to play them it says different error message depending on the player. used VLC, GOM Player Qplayer, seems to be saying unsupported file despite it been mp4.

**Comment by khamayseh** [comment]
Hello Tdammy92. I can not play the decrypted Videos either. Have you got a solution how to make it happen? Thanks in advance for your HELP and answer.
